# Generated by Django 6.0.4 on 2026-04-18 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Deleted at')),
                ('content', models.JSONField(blank=True, default=dict)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notebook', to='projects.node')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Models',
                'abstract': False,
            },
        ),
    ]
